"""Generate a small source/claim inventory from read-only historical evidence."""
import hashlib,json,pathlib,re
P=pathlib.Path(__file__).resolve().parent
def dump(name,obj): (P/name).write_text(json.dumps(obj,indent=2,ensure_ascii=False)+'\n')
records=[json.loads(f.read_text()) for f in sorted((P/'.raw').glob('*.record.json'))]
sources=[{k:v for k,v in r.items() if k!='headers'} for r in records]
by={x['label']:x for x in sources}
details={
 'maintainer-comment':{'publication_utc':'2026-03-24T17:16:19Z','updated_utc':'2026-03-24T17:20:39Z','author':'krrish-berri-2','source_type':'maintainer first-person statement','supports':'CircleCI credentials leaked, including PyPI publish token and GitHub PAT. Does not identify apt or a GitHub Action.'},
 'litellm-official':{'publication_date':'2026-03-24','visible_updates_through':'2026-03-30','source_type':'project official incident page','supports':'Trivy scanning dependency attribution remains qualified; direct PyPI uploads; still says about 40 minutes. That duration conflicts with the later PyPI platform report.'},
 'litellm-townhall':{'publication_date':'2026-03-27','source_type':'project official incident explanation','supports':'CircleCI shared environment, static release credentials, and unpinned Trivy package running in a scan; incident attribution is framed as present understanding.'},
 'jfrog-analysis':{'publication_date':'2026-03-24','authors':['Guy Korolevski','Andrii Polkovnychenko'],'source_type':'original security research with fixed source link','supports':'Apt-installed Trivy scanner; points to commit 9343aeefca37aa49a6ea54397d7615adae5c72c9.'},
 'trivy-conclusion':{'publication_utc':'2026-03-30T15:12:53Z','author':'itaysk','source_type':'upstream official incident conclusion','updated_utc':None,'date_limit':'Publication time appears in HTML relative-time; no independently verified body edit timestamp. Current text is not an archived March 30 snapshot.','supports':'Trivy initial pull_request_target compromise, cross-account persistence, March 19 release workflow abuse; does not name a LiteLLM-specific GitHub Action ingress.'},
 'aqua-official':{'visible_page_date':'2026-04-01','html_datePublished':'2026-04-01T07:00:11+00:00','html_dateModified':'2026-04-03T21:30:14+00:00','source_type':'upstream vendor incident updates','supports':'Broader campaign included Trivy binaries and trivy-action/setup-trivy tag compromise. Different surfaces must remain distinct.'},
 'futuresearch-disclosure':{'publication_date':'2026-03-24','html_dateModified':'March 30, 2026','source_type':'original discoverer disclosure','supports':'States 1.82.8 lacked matching GitHub tag/release; current page was subsequently edited. Exact first appearance of this sentence is not established.'},
 'futuresearch-count':{'publication_date':'2026-03-25','html_dateModified':'2026-03-25','author':'Daniel Hnyk','source_type':'original researcher download analysis','supports':'Reports 46,996 downloads in a claimed 10:39–11:25 UTC March 24 window. States both malicious versions lacked corresponding tags/releases. Earliest exact-count source located in this bounded search.','method':'Author reports querying BigQuery PyPI download logs; article also uses PyPI JSON and deps.dev for dependency analysis. No full download SQL or raw event table located in the article; query execution time not given.'},
 'pypi-incident':{'publication_date':'2026-04-02','authors':['Seth Larson','Mike Fiedler'],'source_type':'registry operator incident report','supports':'Over 119k downloads; total exposure from upload to quarantine 2h32m. Prefer as later platform report, without inventing exact count or per-version split.','method_limit':'Article provides a timeline chart and rounded durations, not complete event SQL. 1h19m plus 1h12m is 2h31m; retain published 2h32m total without forcing rounded fields to sum.'},
 'pypa-download-guide':{'source_type':'official packaging data documentation','supports':'Linehaul file_downloads stores download events; cache, mirrors and repeated/scripted downloads complicate interpretation. Counts do not establish distinct victims or execution.'}}
for s in sources: s.update(details.get(s['label'],{}))
dump('sources.json',sources)
dump('claims.json',{
 'litellm_entry':{'assessment':'Best-supported public reconstruction: CircleCI invokes ci_cd/security_scans.sh, which installs an unpinned Trivy scanner via apt.','source_labels':['maintainer-comment','litellm-townhall','jfrog-analysis','fixed-security-scans','fixed-circleci'],'boundary':'Official prose retains attribution qualifiers; no original compromised CircleCI run logs or downloaded scanner hash independently reviewed. A GitHub Action is not established as LiteLLM specific ingress.'},
 'broader_chain':{'source_labels':['trivy-conclusion','aqua-official'],'assessment':'Trivy own GitHub Actions and distribution channels were compromised; that fact does not identify the integration mechanism used by a downstream project.'},
 'download_counts':[{'source':'futuresearch-count','date':'2026-03-25','reported_total':46996,'reported_start_utc':'2026-03-24T10:39:00Z','reported_end_utc':'2026-03-24T11:25:00Z','reported_duration_minutes':46,'breakdown':{'1.82.7':14532,'1.82.8':32464,'1.82.8_pip':23142,'1.82.8_uv':8901},'boundary':'Early author-reported result, not independently reproduced; full-window interpretation contradicted by later platform report.'},{'source':'pypi-incident','date':'2026-04-02','reported_total_lower_bound_exclusive':119000,'reported_duration_minutes':152,'reported_upload_to_first_report_minutes':79,'reported_first_report_to_quarantine_minutes':72,'boundary':'Published platform download statistic, not unique victim count. No exact total or precise window endpoints asserted here.'}],
 'quarantine_vs_deletion':{'source':'litellm-townhall','reported_deleted_by_utc':'2026-03-24T16:00:00Z','boundary':'Deletion by 16:00 differs from quarantine time. Do not use deletion as end of the active installation window. Its about-40-minute quarantine statement conflicts with the later PyPI report.'},
 'tags':{'source_labels':['futuresearch-disclosure','futuresearch-count'],'assessment':'Discoverer contemporaneous reporting says no matching tags/releases for the malicious PyPI versions; current disclosure page was edited March 30.','boundary':'No complete historical tag-event audit or archived immutable snapshot obtained; no present-day 404 used to prove historical nonexistence.'},
 'relation_to_current_versions':'These findings concern malicious 1.82.7/1.82.8 in March. They do not establish poisoning of 1.100.0 or 1.101.0rc1.'})
excerpts=[]
for label,repo_path,ranges in [('fixed-security-scans','ci_cd/security_scans.sh',[(10,20),(242,249)]),('fixed-circleci','.circleci/config.yml',[(715,721)])]:
 data=(P/'.raw'/f'{label}.body').read_bytes();lines=data.decode().splitlines()
 excerpts.append({'source':by[label]['url'],'reference_commit':'9343aeefca37aa49a6ea54397d7615adae5c72c9','repository_path':repo_path,'full_source_bytes':len(data),'full_source_sha256':hashlib.sha256(data).hexdigest(),'computed_git_blob_sha1':hashlib.sha1(b'blob '+str(len(data)).encode()+b'\0'+data).hexdigest(),'independent_api_blob_comparison':'Not completed: supplemental contents API returned 403 rate limit exceeded.','excerpts':[{'start_line':a,'end_line':b,'text':'\n'.join(lines[a-1:b])} for a,b in ranges]})
dump('fixed-source-excerpts.json',excerpts)
dump('read-errors.json',{'failed_requests':[x for x in sources if x['http_status']!=200],'action':'Stopped supplemental GitHub contents API checks after rate-limit errors; no retry or alternative credential used. Existing successful raw reads remain explicitly distinguished from independent blob verification.','package_downloads':0,'target_execution':False,'tag_404_checks':0})
print(json.dumps({'requests':len(sources),'http_errors':sum(x['http_status']!=200 for x in sources),'source_entries_with_claims':len(details)}))
